#!/bin/sh
exec tail -n +3 $0

menuentry "Boot from UUID" {
    search --no-floppy --fs-uuid --set=root --hint=usb0,gpt2 --hint=mmcblk0,gpt2 --hint=mmcblk1,gpt2 B921B045-1DF0-41C3-AF44-4C6F280D3FAE
    echo    'Loading 6.16.0-rc7-v8-16k+ ...'
    linux /boot/vmlinuz-6.16.0-rc7-v8-16k+ root=LABEL=rootfs rw rootwait
    echo    'Loading initial ramdisk ...'
    initrd /boot/initrd.img-6.16.0-rc7-v8-16k+
    devicetree /boot/dtb/broadcom/bcm2711-rpi-4-b.dtb
}
